version: 3.6
services:
    web:
        build: ./front-end
        ports:
            - "5173:5173"
        volumes:
            - ./front-end:/code
        depends_on:
            - db
            - backend
    db:
        image: postgres:latest
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        ports:
            - "5432:5432"
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
    redis:
        image: redis:latest
        ports:
            - "6379:6379"
        volumes:
            - ./redis-data:/data

    backend:
        build: ./backend
        ports:
            - "8000:8000"
        volumes:
            - ./backend:/code
        depends_on:
            - db
            - redis