version: 3.6
services:
    web:
        build: 
            context: ./front-end
        ports:
            - "5173:5173"
        volumes:
            - ./front-end:/code:Z
        depends_on:
            - db
            - backend
    db:
        
        image: postgres:13
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        ports:
            - "5432:5432"
        volumes:
            - ./postgres-data:/var/lib/postgresql/data:Z
    redis:
        image: redis:6
        ports:
            - "6379:6379"
        volumes:
            - ./redis-data:/data:Z

    backend:
        build:
            context: ./backend
        ports:
            - "8000:8000"
        volumes:
            - ./backend:/code:Z
        depends_on:
            - db
            - redis