# Generated by Django 4.2.3 on 2023-07-11 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blender', '0002_renderjob_end_frame_renderjob_file_renderjob_otype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renderjob',
            name='oType',
            field=models.CharField(default='PNG', max_length=10),
        ),
    ]
