# Generated by Django 4.2.3 on 2023-07-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blender', '0003_alter_renderjob_otype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renderjob',
            name='progress',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
