# Generated by Django 4.2.3 on 2023-07-09 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='renderjob',
            name='end_frame',
            field=models.IntegerField(default=250),
        ),
        migrations.AddField(
            model_name='renderjob',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='renderjob',
            name='oType',
            field=models.CharField(default='png', max_length=10),
        ),
        migrations.AddField(
            model_name='renderjob',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='renderjob',
            name='start_frame',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='renderjob',
            name='status',
            field=models.CharField(default='NOT_STARTED', max_length=20),
        ),
        migrations.AddField(
            model_name='renderjob',
            name='x_res',
            field=models.IntegerField(default=1920),
        ),
        migrations.AddField(
            model_name='renderjob',
            name='y_res',
            field=models.IntegerField(default=1080),
        ),
    ]
